modLoader="javafml"
loaderVersion="[39,)"
license="Not specified"

[[mods]]
modId="boss_tools"
version="5.6"
displayName="Space-BossTools"
displayURL="https://www.curseforge.com/minecraft/mc-mods/space-bosstools"
logoFile="logo.png"
authors="MrScautHD"
description='''
Fly to Other Planets and Beyond!
'''

[[dependencies.boss_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.boss_tools]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.0,]"
    ordering="NONE"
    side="BOTH"