modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
[[mods]]
modId="beyond_earth_giselle_addon"
version="${file.jarVersion}"
displayName="Beyond Earth: Giselle Addon"
credits="gisellevonbingen"
authors="gisellevonbingen"
description=''''''
[[dependencies.beyond_earth_giselle_addon]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.63,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyond_earth_giselle_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyond_earth_giselle_addon]]
    modId="beyond_earth"
    mandatory=true
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.beyond_earth_giselle_addon]]
    modId="mekanism"
    mandatory=false
    versionRange="[10.0.20,)"
    ordering="AFTER"
    side="BOTH"
