modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="beyond_earth_giselle_addon"
version="${file.jarVersion}"
displayName="Beyond Earth: Giselle Addon"
logoFile="examplemod.png"
credits="gisellevonbingen"
authors="gisellevonbingen"
description=''''''
[[dependencies.beyond_earth_giselle_addon]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyond_earth_giselle_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beyond_earth_giselle_addon]]
    modId="beyond_earth"
    mandatory=true
    versionRange="[5.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.beyond_earth_giselle_addon]]
    modId="mekanism"
    mandatory=false
    versionRange="[10.0.20,)"
    ordering="AFTER"
    side="BOTH"
    