modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="boss_tools_giselle_addon"
version="${file.jarVersion}"
displayName="Space-BossTools: Giselle Addon"
logoFile="examplemod.png"
credits="gisellevonbingen"
authors="gisellevonbingen"
description='''
Just Description
'''
[[dependencies.boss_tools_giselle_addon]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.boss_tools_giselle_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.boss_tools_giselle_addon]]
    modId="boss_tools"
    mandatory=true
    versionRange="[5.5,)"
    ordering="AFTER"
    side="BOTH"
    