modLoader="javafml"
loaderVersion="[${forge_loader_version},)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
    modId="beyond_earth_giselle_addon"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_homepage}"
    authors="gisellevonbingen"
    logoFile="icon.png"
    description='''${mod_description}'''
    itemIcon="beyond_earth_giselle_addon:oxygen_can" #for Catalogue

[[dependencies.ad_astra_giselle_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.ad_astra_giselle_addon]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_api_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_earth_giselle_addon]]
    modId="beyond_earth"
    mandatory=true
    versionRange="[${beyond_earth_version},)"
    ordering="AFTER"
    side="BOTH"
