modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/gisellevonbingen/Minecraft-BossTools-Addon/issues"

[[mods]]
    modId="boss_tools_giselle_addon"
    version="${file.jarVersion}"
    displayName="Space-BossTools: Giselle Addon"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/space-bosstools-giselle-addon"
    authors="gisellevonbingen"
    description='''Just add good things in my think for Space-BossTools'''
    itemIcon="boss_tools_giselle_addon:oxygen_can" #for Catalogue

[[dependencies.boss_tools_giselle_addon]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boss_tools_giselle_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.boss_tools_giselle_addon]]
    modId="boss_tools"
    mandatory=true
    versionRange="[5.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.boss_tools_giselle_addon]]
    modId="mekanism"
    mandatory=false
    versionRange="[10.1.0,)"
    ordering="AFTER"
    side="BOTH"
